"""Add Column

Revision ID: 0b8f6532c6cf
Revises: 7284f4f0e4ba
Create Date: 2022-01-21 12:13:26.143192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8f6532c6cf'
down_revision = '7284f4f0e4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel', sa.Column('flooe', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel', 'flooe')
    # ### end Alembic commands ###
