"""Updated event table

Revision ID: 0c4141c0b8df
Revises: 2b399dba8460
Create Date: 2022-01-29 04:21:32.036449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4141c0b8df'
down_revision = '2b399dba8460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
