"""Removed warden

Revision ID: 1ad43a925d85
Revises: 5be9fe5edb7c
Create Date: 2022-01-26 19:55:26.880434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad43a925d85'
down_revision = '5be9fe5edb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel', 'warden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel', sa.Column('warden', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
