"""Added Eatery Model

Revision ID: 201299b6454c
Revises: f2a70975a324
Create Date: 2022-01-27 02:08:51.412002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '201299b6454c'
down_revision = 'f2a70975a324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eatery',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.Text(), nullable=False),
    sa.Column('lunch', sa.Text(), nullable=False),
    sa.Column('snacks', sa.Text(), nullable=False),
    sa.Column('dinner', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eatery')
    # ### end Alembic commands ###
