"""Updated event table

Revision ID: 2b399dba8460
Revises: d4212717a520
Create Date: 2022-01-29 04:20:43.770027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b399dba8460'
down_revision = 'd4212717a520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
