"""Updated event

Revision ID: 36064da0e557
Revises: 0c4141c0b8df
Create Date: 2022-01-29 13:19:16.796335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36064da0e557'
down_revision = '0c4141c0b8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
