"""Updated event table

Revision ID: d4212717a520
Revises: eff4cecb770e
Create Date: 2022-01-29 04:14:36.636814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4212717a520'
down_revision = 'eff4cecb770e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
