"""Updated event table

Revision ID: e7563267ea3b
Revises: 466490b24957
Create Date: 2022-01-29 03:52:14.963089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7563267ea3b'
down_revision = '466490b24957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
