"""Updated event table

Revision ID: eff4cecb770e
Revises: 2c423d6b2f83
Create Date: 2022-01-29 04:12:30.051869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff4cecb770e'
down_revision = '2c423d6b2f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
