"""Removed Unique contraint

Revision ID: f2a70975a324
Revises: 884001768f91
Create Date: 2022-01-26 22:06:24.909811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a70975a324'
down_revision = '884001768f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hostel_name_key', 'hostel', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hostel_name_key', 'hostel', ['name'])
    # ### end Alembic commands ###
